apiVersion: apps/v1
kind: Deployment
metadata:
  name: calorie-app
  labels:
    app: calorie-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calorie-app
  template:
    metadata:
      labels:
        app: calorie-app
    spec:
      containers:
        - name: calorie-app
          image: yourdockerhubusername/calorie-app:latest
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
